services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    networks:
      - "fruit_net"
  mongo-seed:
    build: ./mongo_seed
    depends_on:
      - mongodb
    networks:
      - "fruit_net"
  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - "fruit_net"
networks:
 fruit_net:
   driver: bridge